backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "blog-{{day}}-{{month}}-{{year}}"
    fields:
      - { label: "Título", name: "title", widget: "string"}
      - { label: "Fecha", name: "fecha", widget: "string"}
      - { label: "Imagen", name: "imagen", widget: "image"}
      - { label: "Contenido",name: "body", widget: "markdown"}
